#use root/example as user/password credentials
#docker stack deploy -c mysql-compose.yml service
version: '3.1'

services:

  db:
    image: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  adminer:
    image: adminer
    ports:
      - 9081:8080
